name: Trigger Pages Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout article repository
        uses: actions/checkout@v3

      - name: Trigger deploy in chitose1020.github.io
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GH_PAGES_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/chitose1020/chitose1020.github.io/actions/workflows/deployPages.yml/dispatches \
            -d '{"ref":"main"}'
